version: "2"
services:
  api-simple:
    container_name: flask_api_simple
    build:
      context: ../
      dockerfile: devops/api_simple/Dockerfile
    ports:
      - "8000:8000"
  api-view:
    container_name: flask_api_view
    build:
      context: ../
      dockerfile: devops/api_view/Dockerfile
    ports:
      - "8001:8001"
  api-db:
    container_name: flask_api_db
    build:
      context: ../
      dockerfile: devops/api_db/Dockerfile
