CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(64) NOT NULL,
  username VARCHAR(64) UNIQUE NOT NULL,
  email VARCHAR(64) UNIQUE NOT NULL,
  password_hash CHAR(64) UNIQUE NOT NULL,
  password_salt CHAR(36) UNIQUE NOT NULL
);